# Generated by Django 3.2.3 on 2021-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('ticker', models.CharField(max_length=4096)),
                ('activity', models.CharField(max_length=4096)),
                ('comparison', models.CharField(max_length=4096)),
                ('industry', models.CharField(max_length=4096)),
                ('country', models.CharField(max_length=4096)),
                ('rating', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='SPGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('ticker', models.CharField(max_length=4096)),
                ('industry', models.FloatField()),
                ('country', models.CharField(max_length=4096)),
                ('esg_score', models.FloatField()),
                ('environmental_score', models.FloatField()),
                ('social_score', models.FloatField()),
                ('governance_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sustainable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('ticker', models.CharField(max_length=4096)),
                ('esg_rating', models.FloatField()),
                ('risk', models.CharField(max_length=4096)),
            ],
        ),
    ]
